# Generated by Django 3.2.8 on 2021-11-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eveonline', '0014_auto_20210105_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyBackConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_between_updates', models.IntegerField(default=20, help_text='How often should we try to update the orders.')),
                ('corp_filter', models.ManyToManyField(blank=True, help_text='Corporations to show in the list', to='eveonline.EveCorporationInfo')),
            ],
            options={
                'permissions': (('basic_access', 'Can access buybacks module.'),),
            },
        ),
    ]
