# Generated by Django 3.2.8 on 2021-11-26 07:27

from django.db import migrations

def add_settings(apps, schema_editor):
    BuyBackConfig = apps.get_model('ctbuybacks', 'BuyBackConfig')

    #StructureLostShields
    BuyBackConfig.objects.create()


class Migration(migrations.Migration):

    dependencies = [
        ('ctbuybacks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_settings)
    ]
